### ISSUE TITLE
Uncaught TypeError: editor.getUri is not a function

### ISSUE THREAD

**Issue by krasnovpro** [js-padavan/atom-css-class-checker#8]
[Enter steps to reproduce below:]
1. place cursot to class name: <nav class="navbar">
2. hit ctrl-b

**Atom Version**: 1.3.0-beta4
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-css-class-checker](https://github.com/js-padavan/atom-css-class-checker) package, v0.4.3
### Stack Trace

Uncaught TypeError: editor.getUri is not a function

```
At /Users/oleg/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:244

TypeError: editor.getUri is not a function
    at /Users/oleg/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:244:40
    at Manager.openSource (/Users/oleg/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:272:18)
    at atom-workspace.Manager.atom.commands.add.atom-css-class-checker:open-source (/Users/oleg/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:25:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Dev/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:56.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:55.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:55.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:54.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:51.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.3.0 atom-css-class-checker:toggle (atom-text-editor.editor)
     -0:50.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:49.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:49 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:48.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:47.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.1.0 atom-css-class-checker:toggle (atom-text-editor.editor)
  2x -0:43.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:42.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:06.2.0 atom-css-class-checker:open-source (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "vim-mode",
      "quick-jump",
      "save-session",
      "vim-mode-plus"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "last-cursor-position",
      "multi-cursor",
      "tab-switcher"
    ]
  },
  "atom-css-class-checker": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-alignment, v0.12.1
atom-css-class-checker, v0.4.3
atom-image-resize, v0.3.0
atom-jade, v0.3.0
atom-lorempixel, v0.1.0
atom-vim-colon-command-on-command-pallete, v0.1.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
emmet, v2.3.14
file-icon-supplement, v0.8.3
highlight-selected, v0.11.1
language-apache, v1.3.0
language-nginx, v0.6.1
language-postcss, v1.1.0
last-cursor-position, v0.9.0
linter, v1.11.2
linter-jade, v0.3.2
local-history, v3.2.3
minimap, v4.16.1
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
minimap-split-diff, v0.2.1
newton-dark-syntax, v1.1.5
newton-dark-ui, v1.0.9
open-recent, v4.0.1
pigments, v0.19.0
preview-inline, v0.5.1
set-syntax, v0.3.0
table-editor, v0.1.1
ult-terminal, v0.2.0

# Dev
No dev packages
```

**Comment by csakis** [comment]
same problem here.

**Comment by yougotashovel** [comment]
I'm getting same problem too

**Comment by noistudio** [comment]
Hi trying to install version from my repository 
https://github.com/noistudio/atom-css-class-checker
