### ISSUE TITLE
Uncaught TypeError: editor.getUri is not a function

### ISSUE THREAD

**Issue by Marsovski** [js-padavan/atom-css-class-checker#9]
[Enter steps to reproduce below:]
1. place cursor to class name
2. hit ctrl-b

**Atom Version**: 1.3.2
**System**: Linux Mint
**Thrown From**: [atom-css-class-checker](https://github.com/js-padavan/atom-css-class-checker) package, v0.4.3
### Stack Trace

Uncaught TypeError: editor.getUri is not a function

```
At /home/milos/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:244

TypeError: editor.getUri is not a function
    at /home/milos/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:244:40
    at Manager.openSource (/home/milos/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:272:18)
    at atom-workspace.Manager.atom.commands.add.atom-css-class-checker:open-source (/home/milos/.atom/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:25:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:54.6.0 atom-css-class-checker:toggle (atom-text-editor.editor.is-focused)
     -0:53.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:52.8.0 atom-css-class-checker:open-source (atom-text-editor.editor.is-focused)
     -0:52.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:50.9.0 atom-css-class-checker:open-source (atom-text-editor.editor.is-focused)
     -0:50.7.0 editor:move-line-down (atom-text-editor.editor.is-focused)
  6x -0:49.6.0 atom-css-class-checker:open-source (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "icon-fonts"
    ]
  },
  "atom-css-class-checker": {}
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-css-class-checker, v0.4.3
atom-typescript, v7.14.3
docblockr, v0.7.3
dot-hide, v1.5.0
file-icons, v1.6.13
font-awesome-snippetset, v0.0.6
git-hide, v0.1.2
git-log, v0.4.1
hide-files, v0.1.7
language-typescript-grammars-only, v1.3.0
linter, v1.11.3
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
terminal-plus, v0.14.5
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```

**Comment by noistudio** [comment]
Hi!
Trying to install version from my repository.
https://github.com/noistudio/atom-css-class-checker

**Comment by ariferol01** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-css-class-checker](https://github.com/js-padavan/atom-css-class-checker) package 0.4.3


### Stack Trace

Uncaught TypeError: editor.getUri is not a function

```
At C:\Users\Arif\.atom\packages\atom-css-class-checker\lib\atom-css-class-checker-manager.coffee:244

TypeError: editor.getUri is not a function
    at /packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:244:40
    at Manager.openSource (/packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:272:18)
    at /packages/atom-css-class-checker/lib/atom-css-class-checker-manager.coffee:25:8)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -6:05.3.0 atom-css-class-checker:toggle (input.hidden-input)
     -5:52.5.0 core:backspace (input.hidden-input)
  3x -5:31.2.0 atom-css-class-checker:toggle (span.syntax--string.syntax--quoted.syntax--double.syntax--html)
     -4:45.7.0 editor:newline (input.hidden-input)
  2x -4:37.7.0 core:backspace (input.hidden-input)
     -4:34.7.0 editor:newline (input.hidden-input)
 24x -4:34 core:backspace (input.hidden-input)
     -4:15 atom-css-class-checker:toggle (input.hidden-input)
     -4:13.4.0 application:open-file (input.hidden-input)
     -3:02.4.0 atom-css-class-checker:toggle (input.hidden-input)
  3x -2:40.8.0 atom-css-class-checker:open-source (input.hidden-input)
     -0:23.3.0 core:backspace (input.hidden-input)
  2x -0:20.9.0 atom-css-class-checker:toggle (input.hidden-input)
     -0:16.2.0 atom-css-class-checker:open-source (input.hidden-input)
     -0:11.2.0 atom-css-class-checker:toggle (input.hidden-input)
     -0:08.2.0 atom-css-class-checker:open-source (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-css-class-checker 0.4.3 
color-picker 2.2.5 
ftp-remote-edit 0.12.7 
my-package 0.0.0 
selector-to-tag 0.4.2 
snippet-generator 0.3.2 
teletype 0.4.0 
```
